/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-01-07 11:29:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lib.book.shop.to.*;

public final class searchBook_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1734970757686L));
    _jspx_dependants.put("jar:file:/D:/PRATEEK/Preparation/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Online%20BookStore/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
    _jspx_dependants.put("/WEB-INF/tlds/Libindia.tld", Long.valueOf(1736152942018L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.lib.book.shop.to");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flib_005fshowEdition_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flib_005fshowSortField_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flib_005fshowSortOrder_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flib_005fshowEdition_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flib_005fshowSortField_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flib_005fshowSortOrder_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005flib_005fshowEdition_005fnobody.release();
    _005fjspx_005ftagPool_005flib_005fshowSortField_005fnobody.release();
    _005fjspx_005ftagPool_005flib_005fshowSortOrder_005fnobody.release();
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Lib Book Store</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/css/Libindia.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=searchBook.lib method=\"post\">\r\n");
      out.write("		<center>\r\n");
      out.write("			<table width=\"95%\" height=\"95%\" align=\"center\">\r\n");
      out.write("				<tr bgcolor=\"orange\">\r\n");
      out.write("					<td align=\"center\" colspan=\"7\"><font size=\"5\"><b>Search\r\n");
      out.write("								Book</b></font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");
      if (_jspx_meth_core_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				<tr valign=\"top\">\r\n");
      out.write("					<td align=\"center\"><b>Book Name</b> <input type=\"text\"\r\n");
      out.write("						name=\"bname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BOOK_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("						style=\"color: black; background-color: #b4e0d2;\"></td>\r\n");
      out.write("					<td align=\"center\"><b>Cost</b> <input type=\"text\" name=\"cost\"\r\n");
      out.write("						value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${COST}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"color: black; background-color: #b4e0d2;\">\r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"center\"><b>Author</b> <input type=\"text\"\r\n");
      out.write("						name=\"author\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AUTHOR}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("						style=\"color: black; background-color: #b4e0d2;\"></td>\r\n");
      out.write("					<td align=\"center\"><b>Publication</b> <input type=\"text\"\r\n");
      out.write("						name=\"publication\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PUBLICATION}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("						style=\"color: black; background-color: #b4e0d2;\"></td>\r\n");
      out.write("					<td align=\"center\"><b>Edition</b></td>\r\n");
      out.write("					<td align=\"center\">");
      if (_jspx_meth_lib_005fshowEdition_005f0(_jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td align=\"center\" colspan=\"5\"><input type=\"submit\"\r\n");
      out.write("						value=\"Search\"\r\n");
      out.write("						style=\"color: white; background-color: maroon; font-size: 17\">\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</center>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("	");
      //  core:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_core_005fif_005f1_reused = false;
      try {
        _jspx_th_core_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_core_005fif_005f1.setParent(null);
        // /searchBook.jsp(54,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_core_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BOOK_LIST ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_core_005fif_005f1 = _jspx_th_core_005fif_005f1.doStartTag();
        if (_jspx_eval_core_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("		<form action=\"sortInfo.lib\" method=\"post\">\r\n");
            out.write("			<table width=\"90%\">\r\n");
            out.write("				<tr>\r\n");
            out.write("					<td align=\"left\">");
            if (_jspx_meth_lib_005fshowSortField_005f0(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("</td>\r\n");
            out.write("					<td align=\"left\">");
            if (_jspx_meth_lib_005fshowSortOrder_005f0(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("</td>\r\n");
            out.write("					<td align=\"left\"><input type=\"submit\" value=\"Sort Information\"\r\n");
            out.write("						style=\"color: white; background-color: maroon; font-size: 17\">\r\n");
            out.write("					</td>\r\n");
            out.write("					<td align=\"left\"><font color=\"red\" size=\"4\">");
            if (_jspx_meth_lib_005ferror_005f1(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("</font></td>\r\n");
            out.write("					<td align=\"right\" colspan=\"7\"><font color=\"maroon\" size=\"4\"><b>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${START+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("								to ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${END}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" of ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${TOTAL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</b></font></td>\r\n");
            out.write("				</tr>\r\n");
            out.write("			</table>\r\n");
            out.write("		</form>\r\n");
            out.write("\r\n");
            out.write("		<table width=\"90%\" cellspacing=\"0\" cellpadding=\"3\"\r\n");
            out.write("			style=\"font-family: arial\">\r\n");
            out.write("			");
            if (_jspx_meth_core_005fif_005f2(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("			");
            if (_jspx_meth_core_005fif_005f3(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("			");
            if (_jspx_meth_core_005fif_005f4(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("			<tr bgcolor=\"black\">\r\n");
            out.write("				<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Sr.No</b></font>\r\n");
            out.write("				</td>\r\n");
            out.write("				<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>BookName</b></font>\r\n");
            out.write("				</td>\r\n");
            out.write("				<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Author</b></font>\r\n");
            out.write("				</td>\r\n");
            out.write("				<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Publication</b></font>\r\n");
            out.write("				</td>\r\n");
            out.write("				<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Edition</b></font>\r\n");
            out.write("				</td>\r\n");
            out.write("				");
            if (_jspx_meth_core_005fif_005f5(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("				");
            if (_jspx_meth_core_005fif_005f6(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("				");
            if (_jspx_meth_core_005fif_005f7(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("			</tr>\r\n");
            out.write("\r\n");
            out.write("			");

			int i = Integer.parseInt(session.getAttribute("START").toString());
			int x = -1;
			String color = "#fdeaff";
			
            out.write("\r\n");
            out.write("\r\n");
            out.write("			");
            //  core:forEach
            org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
            boolean _jspx_th_core_005fforEach_005f0_reused = false;
            try {
              _jspx_th_core_005fforEach_005f0.setPageContext(_jspx_page_context);
              _jspx_th_core_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
              // /searchBook.jsp(125,3) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_core_005fforEach_005f0.setVar("bto");
              // /searchBook.jsp(125,3) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
              _jspx_th_core_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/searchBook.jsp(125,3) '${BOOK_LIST}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${BOOK_LIST}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
              int[] _jspx_push_body_count_core_005fforEach_005f0 = new int[] { 0 };
              try {
                int _jspx_eval_core_005fforEach_005f0 = _jspx_th_core_005fforEach_005f0.doStartTag();
                if (_jspx_eval_core_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                  do {
                    out.write("\r\n");
                    out.write("				");

				++i;
				x++;
				if (x == 3)
					x = 0;
				if (x == 0)
					color = "fdeaff";
				else if (x == 1)
					color = "#dee1fe";
				else if (x == 2)
					color = "#e1ffde";
				
                    out.write("\r\n");
                    out.write("				<tr bgcolor=\"");
                    out.print(color);
                    out.write("\">\r\n");
                    out.write("					<td align=\"center\"><b>");
                    out.print(i);
                    out.write("</b></td>\r\n");
                    out.write("					<td align=\"center\"><font size=\"4\">");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.bookName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("</font></td>\r\n");
                    out.write("					<td align=\"center\"><font size=\"4\">");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("</font></td>\r\n");
                    out.write("					<td align=\"center\"><font size=\"4\">");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.publication}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("</font></td>\r\n");
                    out.write("					<td align=\"center\"><font size=\"4\">");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.edition}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("</font></td>\r\n");
                    out.write("					<td><font size=\"4\" face=\"Rupee Foradian\"></font><font size=\"4\">");
                    out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.cost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                    out.write("</font>\r\n");
                    out.write("					</td>\r\n");
                    out.write("					<td align=\"center\">");
                    if (_jspx_meth_core_005fif_005f8(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
                      return;
                    out.write(' ');
                    if (_jspx_meth_core_005fif_005f9(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
                      return;
                    out.write("</td>\r\n");
                    out.write("				</tr>\r\n");
                    out.write("			");
                    int evalDoAfterBody = _jspx_th_core_005fforEach_005f0.doAfterBody();
                    if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                      break;
                  } while (true);
                }
                if (_jspx_th_core_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                  return;
                }
              } catch (java.lang.Throwable _jspx_exception) {
                while (_jspx_push_body_count_core_005fforEach_005f0[0]-- > 0)
                  out = _jspx_page_context.popBody();
                _jspx_th_core_005fforEach_005f0.doCatch(_jspx_exception);
              } finally {
                _jspx_th_core_005fforEach_005f0.doFinally();
              }
              _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f0);
              _jspx_th_core_005fforEach_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_core_005fforEach_005f0_reused);
            }
            out.write("\r\n");
            out.write("\r\n");
            out.write("			");
            if (_jspx_meth_core_005fif_005f10(_jspx_th_core_005fif_005f1, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("		</table>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_core_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_core_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f1);
        _jspx_th_core_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f1_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_core_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f0_reused = false;
    try {
      _jspx_th_core_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f0.setParent(null);
      // /searchBook.jsp(22,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchingBookError ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f0 = _jspx_th_core_005fif_005f0.doStartTag();
      if (_jspx_eval_core_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<tr bgcolor=\"lightyellow\">\r\n");
          out.write("						<td align=\"center\" colspan=\"6\"><font color=\"red\" size=\"4\"><b>");
          if (_jspx_meth_lib_005ferror_005f0(_jspx_th_core_005fif_005f0, _jspx_page_context))
            return true;
          out.write("</b></font></td>\r\n");
          out.write("					</tr>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_core_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f0);
      _jspx_th_core_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lib_005ferror_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lib:error
    com.lib.book.shop.tags.ErrorTag _jspx_th_lib_005ferror_005f0 = (com.lib.book.shop.tags.ErrorTag) _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody.get(com.lib.book.shop.tags.ErrorTag.class);
    boolean _jspx_th_lib_005ferror_005f0_reused = false;
    try {
      _jspx_th_lib_005ferror_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lib_005ferror_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f0);
      // /searchBook.jsp(24,67) name = property type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lib_005ferror_005f0.setProperty("searchingBookError");
      int _jspx_eval_lib_005ferror_005f0 = _jspx_th_lib_005ferror_005f0.doStartTag();
      if (_jspx_th_lib_005ferror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody.reuse(_jspx_th_lib_005ferror_005f0);
      _jspx_th_lib_005ferror_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lib_005ferror_005f0, _jsp_getInstanceManager(), _jspx_th_lib_005ferror_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lib_005fshowEdition_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lib:showEdition
    com.lib.book.shop.tags.ShowEditionTag _jspx_th_lib_005fshowEdition_005f0 = (com.lib.book.shop.tags.ShowEditionTag) _005fjspx_005ftagPool_005flib_005fshowEdition_005fnobody.get(com.lib.book.shop.tags.ShowEditionTag.class);
    boolean _jspx_th_lib_005fshowEdition_005f0_reused = false;
    try {
      _jspx_th_lib_005fshowEdition_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lib_005fshowEdition_005f0.setParent(null);
      int _jspx_eval_lib_005fshowEdition_005f0 = _jspx_th_lib_005fshowEdition_005f0.doStartTag();
      if (_jspx_th_lib_005fshowEdition_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flib_005fshowEdition_005fnobody.reuse(_jspx_th_lib_005fshowEdition_005f0);
      _jspx_th_lib_005fshowEdition_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lib_005fshowEdition_005f0, _jsp_getInstanceManager(), _jspx_th_lib_005fshowEdition_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lib_005fshowSortField_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lib:showSortField
    com.lib.book.shop.tags.ShowSortFieldTag _jspx_th_lib_005fshowSortField_005f0 = (com.lib.book.shop.tags.ShowSortFieldTag) _005fjspx_005ftagPool_005flib_005fshowSortField_005fnobody.get(com.lib.book.shop.tags.ShowSortFieldTag.class);
    boolean _jspx_th_lib_005fshowSortField_005f0_reused = false;
    try {
      _jspx_th_lib_005fshowSortField_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lib_005fshowSortField_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      int _jspx_eval_lib_005fshowSortField_005f0 = _jspx_th_lib_005fshowSortField_005f0.doStartTag();
      if (_jspx_th_lib_005fshowSortField_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flib_005fshowSortField_005fnobody.reuse(_jspx_th_lib_005fshowSortField_005f0);
      _jspx_th_lib_005fshowSortField_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lib_005fshowSortField_005f0, _jsp_getInstanceManager(), _jspx_th_lib_005fshowSortField_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lib_005fshowSortOrder_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lib:showSortOrder
    com.lib.book.shop.tags.ShowSortFieldTag _jspx_th_lib_005fshowSortOrder_005f0 = (com.lib.book.shop.tags.ShowSortFieldTag) _005fjspx_005ftagPool_005flib_005fshowSortOrder_005fnobody.get(com.lib.book.shop.tags.ShowSortFieldTag.class);
    boolean _jspx_th_lib_005fshowSortOrder_005f0_reused = false;
    try {
      _jspx_th_lib_005fshowSortOrder_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lib_005fshowSortOrder_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      int _jspx_eval_lib_005fshowSortOrder_005f0 = _jspx_th_lib_005fshowSortOrder_005f0.doStartTag();
      if (_jspx_th_lib_005fshowSortOrder_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flib_005fshowSortOrder_005fnobody.reuse(_jspx_th_lib_005fshowSortOrder_005f0);
      _jspx_th_lib_005fshowSortOrder_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lib_005fshowSortOrder_005f0, _jsp_getInstanceManager(), _jspx_th_lib_005fshowSortOrder_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lib_005ferror_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lib:error
    com.lib.book.shop.tags.ErrorTag _jspx_th_lib_005ferror_005f1 = (com.lib.book.shop.tags.ErrorTag) _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody.get(com.lib.book.shop.tags.ErrorTag.class);
    boolean _jspx_th_lib_005ferror_005f1_reused = false;
    try {
      _jspx_th_lib_005ferror_005f1.setPageContext(_jspx_page_context);
      _jspx_th_lib_005ferror_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      // /searchBook.jsp(63,49) name = property type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lib_005ferror_005f1.setProperty("sortingError");
      int _jspx_eval_lib_005ferror_005f1 = _jspx_th_lib_005ferror_005f1.doStartTag();
      if (_jspx_th_lib_005ferror_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody.reuse(_jspx_th_lib_005ferror_005f1);
      _jspx_th_lib_005ferror_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lib_005ferror_005f1, _jsp_getInstanceManager(), _jspx_th_lib_005ferror_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f2_reused = false;
    try {
      _jspx_th_core_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      // /searchBook.jsp(73,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ DELETE_MESSAGE ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f2 = _jspx_th_core_005fif_005f2.doStartTag();
      if (_jspx_eval_core_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<tr>\r\n");
          out.write("					<td colspan=\"7\" align=\"center\" bgcolor=\"lightyellow\"><font\r\n");
          out.write("						color=\"red\" size=\"3\"><b>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${DELETE_MESSAGE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b></font></td>\r\n");
          out.write("				</tr>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_core_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f2);
      _jspx_th_core_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f3_reused = false;
    try {
      _jspx_th_core_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      // /searchBook.jsp(79,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ ADDED_TO_CART_MESSAGE ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f3 = _jspx_th_core_005fif_005f3.doStartTag();
      if (_jspx_eval_core_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<tr>\r\n");
          out.write("					<td colspan=\"7\" align=\"center\" bgcolor=\"lightyellow\"><b><font\r\n");
          out.write("							color=\"black\" size=\"4\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ADDED_BOOK.bookName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</font> <font\r\n");
          out.write("							color=\"red\" size=\"4\">added to Cart.Quantity of<font\r\n");
          out.write("								color=\"black\" size=\"4\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ADDED_BOOK.bookName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</font>is<font\r\n");
          out.write("								color=\"green\" size=\"4\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ADDED_BOOK.selectedNumberOfBook}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</font>\r\n");
          out.write("						</font> </b></td>\r\n");
          out.write("				</tr>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_core_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f3);
      _jspx_th_core_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f4_reused = false;
    try {
      _jspx_th_core_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      // /searchBook.jsp(89,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${REMOVED_TOTAL ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f4 = _jspx_th_core_005fif_005f4.doStartTag();
      if (_jspx_eval_core_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<tr>\r\n");
          out.write("					<td colspan=\"7\" align=\"center\" bgcolor=\"lightyellow\"><font\r\n");
          out.write("						color=\"red\" size=\"4\"><b>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${REMOVED_TOTAL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b></font></td>\r\n");
          out.write("				</tr>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_core_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f4);
      _jspx_th_core_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f5_reused = false;
    try {
      _jspx_th_core_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      // /searchBook.jsp(106,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SELECTED_BOOK_LIST eq null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f5 = _jspx_th_core_005fif_005f5.doStartTag();
      if (_jspx_eval_core_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<td colspan=\"2\" align=\"center\"><font color=\"yellow\" size=\"5\"><b>Cost</b></font></td>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_core_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f5);
      _jspx_th_core_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f6_reused = false;
    try {
      _jspx_th_core_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      // /searchBook.jsp(109,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SELECTED_BOOK_LIST ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f6 = _jspx_th_core_005fif_005f6.doStartTag();
      if (_jspx_eval_core_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Cost</b></font></td>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_core_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f6);
      _jspx_th_core_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f7_reused = false;
    try {
      _jspx_th_core_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      // /searchBook.jsp(112,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SELECTED_BOOK_LIST ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f7 = _jspx_th_core_005fif_005f7.doStartTag();
      if (_jspx_eval_core_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<td bgcolor=\"maroon\" align=\"center\"><a href=\"showCartDef.jsp\">\r\n");
          out.write("							<font size=\"5\"><b>Show My Cart</b></font>\r\n");
          out.write("					</a></td>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_core_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f7);
      _jspx_th_core_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f8_reused = false;
    try {
      _jspx_th_core_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
      // /searchBook.jsp(146,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${USER_TO.role eq 'Admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f8 = _jspx_th_core_005fif_005f8.doStartTag();
      if (_jspx_eval_core_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<form action=\"delete.lib\" method=\"post\">\r\n");
          out.write("								<input type=\"hidden\" name=\"bookId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<input type=\"submit\" value=\"Delete\">\r\n");
          out.write("							</form>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_core_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f8);
      _jspx_th_core_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f9_reused = false;
    try {
      _jspx_th_core_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
      // /searchBook.jsp(151,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${USER_TO.role eq 'User'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f9 = _jspx_th_core_005fif_005f9.doStartTag();
      if (_jspx_eval_core_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<form action=\"addtocart.lib\" method=\"post\">\r\n");
          out.write("								<input type=\"hidden\" name=\"bookId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("								<input type=\"submit\" value=\"Add to Cart\">\r\n");
          out.write("							</form>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_core_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f9);
      _jspx_th_core_005fif_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f10 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f10_reused = false;
    try {
      _jspx_th_core_005fif_005f10.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f1);
      // /searchBook.jsp(160,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f10.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${TOTAL gt 5}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f10 = _jspx_th_core_005fif_005f10.doStartTag();
      if (_jspx_eval_core_005fif_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<tr bgcolor=\"maroon\">\r\n");
          out.write("					<td colspan=\"4\" align=\"left\">");
          if (_jspx_meth_core_005fif_005f11(_jspx_th_core_005fif_005f10, _jspx_page_context))
            return true;
          out.write("</td>\r\n");
          out.write("\r\n");
          out.write("					<td align=\"right\" colspan=\"3\">");
          if (_jspx_meth_core_005fif_005f12(_jspx_th_core_005fif_005f10, _jspx_page_context))
            return true;
          out.write("</td>\r\n");
          out.write("				</tr>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_core_005fif_005f10.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f10);
      _jspx_th_core_005fif_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f10, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f10, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f11 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f11_reused = false;
    try {
      _jspx_th_core_005fif_005f11.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f10);
      // /searchBook.jsp(162,34) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f11.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${START gt 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f11 = _jspx_th_core_005fif_005f11.doStartTag();
      if (_jspx_eval_core_005fif_005f11 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<a href=\"previous.lib\"><font size=\"4\"><b>Previous</b></font>\r\n");
          out.write("							</a>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_core_005fif_005f11.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f11);
      _jspx_th_core_005fif_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f11, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f12(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f10, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f12 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f12_reused = false;
    try {
      _jspx_th_core_005fif_005f12.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f12.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f10);
      // /searchBook.jsp(167,35) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f12.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${END lt TOTAL}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f12 = _jspx_th_core_005fif_005f12.doStartTag();
      if (_jspx_eval_core_005fif_005f12 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("							<a href=\"next.lib\"><font size=\"4\"><b>Next</b></font> </a>\r\n");
          out.write("						");
          int evalDoAfterBody = _jspx_th_core_005fif_005f12.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f12);
      _jspx_th_core_005fif_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f12, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f12_reused);
    }
    return false;
  }
}
