/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-01-07 13:31:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.lib.book.shop.to.*;

public final class showCart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1734970757686L));
    _jspx_dependants.put("jar:file:/D:/PRATEEK/Preparation/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Online%20BookStore/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
    _jspx_dependants.put("/WEB-INF/tlds/Libindia.tld", Long.valueOf(1736152942018L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.lib.book.shop.to");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flib_005fdisplayBookTotalAmount_0026_005fvalue_005fquantity_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flib_005fdisplayTotalAmount_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flib_005fdisplayBookTotalAmount_0026_005fvalue_005fquantity_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flib_005fdisplayTotalAmount_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005flib_005fdisplayBookTotalAmount_0026_005fvalue_005fquantity_005fnobody.release();
    _005fjspx_005ftagPool_005flib_005fdisplayTotalAmount_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Lib Book Store</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/css/Libindia.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<center>\r\n");
      out.write("		<form action=\"removefromcart.lib\" method=\"post\">\r\n");
      out.write("			<table width=\"90%\" cellspacing=\"0\" cellpadding=\"3\"\r\n");
      out.write("				style=\"font-family: arial\">\r\n");
      out.write("				<tr bgcolor=\"orange\">\r\n");
      out.write("					<td align=\"center\" colspan=\"8\"><font size=\"5\"><b>Displaying\r\n");
      out.write("								book from Cart</b></font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr bgcolor=\"lightyellow\">\r\n");
      out.write("					<td align=\"center\" colspan=\"7\"><font color=\"red\" size=\"4\">");
      if (_jspx_meth_lib_005ferror_005f0(_jspx_page_context))
        return;
      out.write("</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				");
      if (_jspx_meth_core_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				<tr bgcolor=\"black\">\r\n");
      out.write("					<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>BookName</b></font>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Author</b></font>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Publication</b></font>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Edition</b></font>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Cost</b></font>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Quantity</b></font>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"center\"><font color=\"yellow\" size=\"5\"><b>Total</b></font>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				");

				int i = 0;
				int x = -1;
				String color = "#fdeaff";
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      //  core:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_core_005fforEach_005f0_reused = false;
      try {
        _jspx_th_core_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_core_005fforEach_005f0.setParent(null);
        // /showCart.jsp(58,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_core_005fforEach_005f0.setVar("bto");
        // /showCart.jsp(58,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_core_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/showCart.jsp(58,4) '${SELECTED_BOOK_LIST}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${SELECTED_BOOK_LIST}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        int[] _jspx_push_body_count_core_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_core_005fforEach_005f0 = _jspx_th_core_005fforEach_005f0.doStartTag();
          if (_jspx_eval_core_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("					");

					++i;
					x++;
					if (x == 3)
						x = 0;
					if (x == 0)
						color = "fdeaff";
					else if (x == 1)
						color = "#dee1fe";
					else if (x == 2)
						color = "#e1ffde";
					
              out.write("\r\n");
              out.write("					<tr bgcolor=\"");
              out.print(color);
              out.write("\">\r\n");
              out.write("						<td><input type=\"radio\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.bookId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" name=\"bookId\">\r\n");
              out.write("							<font size=\"4\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.bookName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</font></td>\r\n");
              out.write("						<td align=\"center\"><font size=\"4\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</font></td>\r\n");
              out.write("						<td align=\"center\"><font size=\"4\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.publication}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</font></td>\r\n");
              out.write("						<td align=\"center\"><font size=\"4\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.edition}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</font></td>\r\n");
              out.write("						<td align=\"right\"><font size=\"4\" face=\"Rupee Foradian\"></font><font\r\n");
              out.write("							size=\"4\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.cost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("/-</font></td>\r\n");
              out.write("						<td align=\"center\"><font size=\"4\">");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.selectedNumberOfBook}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</font></td>\r\n");
              out.write("						<td align=\"right\"><font size=\"4\" face=\"Rupee Foradian\"></font><font\r\n");
              out.write("							size=\"4\"> ");
              if (_jspx_meth_lib_005fdisplayBookTotalAmount_005f0(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
                return;
              out.write("/-\r\n");
              out.write("						</font></td>\r\n");
              out.write("					</tr>\r\n");
              out.write("				");
              int evalDoAfterBody = _jspx_th_core_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_core_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_core_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_core_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_core_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f0);
        _jspx_th_core_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_core_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<tr bgcolor=\"#ff8080\">\r\n");
      out.write("					<td colspan=\"5\" align=\"right\"><font color=\"\" size=\"4\"><b>Total</b></font>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"center\"><font color=\"\" size=\"4\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${TOTAL_BOOK_QUANTITY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></font>\r\n");
      out.write("					</td>\r\n");
      out.write("					<td align=\"right\"><font size=\"4\" face=\"Rupee Foradian\">");
      if (_jspx_meth_lib_005fdisplayTotalAmount_005f0(_jspx_page_context))
        return;
      out.write("/-\r\n");
      out.write("					</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr bgcolor=\"maroon\">\r\n");
      out.write("					<td colspan=\"2\" align=\"center\"><a href=\"searchBookDef.jsp\"><font\r\n");
      out.write("							size=\"3\">Add More Book</font> </a></td>\r\n");
      out.write("					<td colspan=\"3\" align=\"center\"><a href=\"placeOrderDef.jsp\"><font\r\n");
      out.write("							size=\"3\">Place Order</font> </a></td>\r\n");
      out.write("					<td colspan=\"2\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("						value=\"Remove\" class=\"signoutButton\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_lib_005ferror_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lib:error
    com.lib.book.shop.tags.ErrorTag _jspx_th_lib_005ferror_005f0 = (com.lib.book.shop.tags.ErrorTag) _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody.get(com.lib.book.shop.tags.ErrorTag.class);
    boolean _jspx_th_lib_005ferror_005f0_reused = false;
    try {
      _jspx_th_lib_005ferror_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lib_005ferror_005f0.setParent(null);
      // /showCart.jsp(24,63) name = property type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lib_005ferror_005f0.setProperty("bookId");
      int _jspx_eval_lib_005ferror_005f0 = _jspx_th_lib_005ferror_005f0.doStartTag();
      if (_jspx_th_lib_005ferror_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flib_005ferror_0026_005fproperty_005fnobody.reuse(_jspx_th_lib_005ferror_005f0);
      _jspx_th_lib_005ferror_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lib_005ferror_005f0, _jsp_getInstanceManager(), _jspx_th_lib_005ferror_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_core_005fif_005f0_reused = false;
    try {
      _jspx_th_core_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_core_005fif_005f0.setParent(null);
      // /showCart.jsp(27,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_core_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${REMOVED_BOOK ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_core_005fif_005f0 = _jspx_th_core_005fif_005f0.doStartTag();
      if (_jspx_eval_core_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<tr bgcolor=\"lightyellow\">\r\n");
          out.write("						<td align=\"center\" colspan=\"8\"><b><font size=\"4\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${REMOVED_BOOK.bookName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</font><font\r\n");
          out.write("								color=\"red\" size=\"4\"> is removed successfully. Quantity\r\n");
          out.write("									was</font><font color=\"green\" size=\"4\">\r\n");
          out.write("									");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${REMOVED_BOOK.selectedNumberOfBook}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</font></b></td>\r\n");
          out.write("					</tr>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_core_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f0);
      _jspx_th_core_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_core_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_core_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lib_005fdisplayBookTotalAmount_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lib:displayBookTotalAmount
    com.lib.book.shop.tags.BookAmountTag _jspx_th_lib_005fdisplayBookTotalAmount_005f0 = (com.lib.book.shop.tags.BookAmountTag) _005fjspx_005ftagPool_005flib_005fdisplayBookTotalAmount_0026_005fvalue_005fquantity_005fnobody.get(com.lib.book.shop.tags.BookAmountTag.class);
    boolean _jspx_th_lib_005fdisplayBookTotalAmount_005f0_reused = false;
    try {
      _jspx_th_lib_005fdisplayBookTotalAmount_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lib_005fdisplayBookTotalAmount_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
      // /showCart.jsp(81,17) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lib_005fdisplayBookTotalAmount_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.cost * bto.selectedNumberOfBook}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /showCart.jsp(81,17) name = quantity type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_lib_005fdisplayBookTotalAmount_005f0.setQuantity((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bto.selectedNumberOfBook}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_lib_005fdisplayBookTotalAmount_005f0 = _jspx_th_lib_005fdisplayBookTotalAmount_005f0.doStartTag();
      if (_jspx_th_lib_005fdisplayBookTotalAmount_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flib_005fdisplayBookTotalAmount_0026_005fvalue_005fquantity_005fnobody.reuse(_jspx_th_lib_005fdisplayBookTotalAmount_005f0);
      _jspx_th_lib_005fdisplayBookTotalAmount_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lib_005fdisplayBookTotalAmount_005f0, _jsp_getInstanceManager(), _jspx_th_lib_005fdisplayBookTotalAmount_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_lib_005fdisplayTotalAmount_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  lib:displayTotalAmount
    com.lib.book.shop.tags.TotalAmountTag _jspx_th_lib_005fdisplayTotalAmount_005f0 = (com.lib.book.shop.tags.TotalAmountTag) _005fjspx_005ftagPool_005flib_005fdisplayTotalAmount_005fnobody.get(com.lib.book.shop.tags.TotalAmountTag.class);
    boolean _jspx_th_lib_005fdisplayTotalAmount_005f0_reused = false;
    try {
      _jspx_th_lib_005fdisplayTotalAmount_005f0.setPageContext(_jspx_page_context);
      _jspx_th_lib_005fdisplayTotalAmount_005f0.setParent(null);
      int _jspx_eval_lib_005fdisplayTotalAmount_005f0 = _jspx_th_lib_005fdisplayTotalAmount_005f0.doStartTag();
      if (_jspx_th_lib_005fdisplayTotalAmount_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005flib_005fdisplayTotalAmount_005fnobody.reuse(_jspx_th_lib_005fdisplayTotalAmount_005f0);
      _jspx_th_lib_005fdisplayTotalAmount_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_lib_005fdisplayTotalAmount_005f0, _jsp_getInstanceManager(), _jspx_th_lib_005fdisplayTotalAmount_005f0_reused);
    }
    return false;
  }
}
