/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.84
 * Generated at: 2025-01-07 11:29:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userHomeDef_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1734970757686L));
    _jspx_dependants.put("jar:file:/D:/PRATEEK/Preparation/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Online%20BookStore/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
    _jspx_dependants.put("/WEB-INF/tlds/Libindia.tld", Long.valueOf(1736152942018L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fLib_005fvalidateSession_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fLib_005fremoveSearchInfoFromSessionTag_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fLib_005fvalidateSession_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fLib_005fremoveSearchInfoFromSessionTag_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fLib_005fvalidateSession_005fnobody.release();
    _005fjspx_005ftagPool_005fLib_005fremoveSearchInfoFromSessionTag_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Lib Book Shop</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("href=\"");
      out.print(request.getContextPath());
      out.write("/css/indexstyle.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"lightgray\">\r\n");
      if (_jspx_meth_Lib_005fvalidateSession_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_Lib_005fremoveSearchInfoFromSessionTag_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<table width=\"90%\" align=\"center\" height=\"97%\">\r\n");
      out.write("<tr height=\"5px\" valign=\"top\">\r\n");
      out.write("<td align=\"center\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr valign=\"top\" bgcolor=\"maroon\" height=\"3px\">\r\n");
      out.write("<td align=\"center\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "userMenu.jsp", out, false);
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_Lib_005fvalidateSession_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  Lib:validateSession
    com.lib.book.shop.tags.ValidateSessionTag _jspx_th_Lib_005fvalidateSession_005f0 = (com.lib.book.shop.tags.ValidateSessionTag) _005fjspx_005ftagPool_005fLib_005fvalidateSession_005fnobody.get(com.lib.book.shop.tags.ValidateSessionTag.class);
    boolean _jspx_th_Lib_005fvalidateSession_005f0_reused = false;
    try {
      _jspx_th_Lib_005fvalidateSession_005f0.setPageContext(_jspx_page_context);
      _jspx_th_Lib_005fvalidateSession_005f0.setParent(null);
      int _jspx_eval_Lib_005fvalidateSession_005f0 = _jspx_th_Lib_005fvalidateSession_005f0.doStartTag();
      if (_jspx_th_Lib_005fvalidateSession_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fLib_005fvalidateSession_005fnobody.reuse(_jspx_th_Lib_005fvalidateSession_005f0);
      _jspx_th_Lib_005fvalidateSession_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_Lib_005fvalidateSession_005f0, _jsp_getInstanceManager(), _jspx_th_Lib_005fvalidateSession_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_Lib_005fremoveSearchInfoFromSessionTag_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  Lib:removeSearchInfoFromSessionTag
    com.lib.book.shop.tags.RemoveSearchInfoFromSessionTag _jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0 = (com.lib.book.shop.tags.RemoveSearchInfoFromSessionTag) _005fjspx_005ftagPool_005fLib_005fremoveSearchInfoFromSessionTag_005fnobody.get(com.lib.book.shop.tags.RemoveSearchInfoFromSessionTag.class);
    boolean _jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0_reused = false;
    try {
      _jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0.setPageContext(_jspx_page_context);
      _jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0.setParent(null);
      int _jspx_eval_Lib_005fremoveSearchInfoFromSessionTag_005f0 = _jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0.doStartTag();
      if (_jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fLib_005fremoveSearchInfoFromSessionTag_005fnobody.reuse(_jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0);
      _jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0, _jsp_getInstanceManager(), _jspx_th_Lib_005fremoveSearchInfoFromSessionTag_005f0_reused);
    }
    return false;
  }
}
